Parameters:
  awsPolicyParameterOne:
    Type: String
    Default: arn:aws:iam::aws:policy/SecretsManagerReadWrite
    AllowedValues: 
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite

Resources:
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: secreatManagerPermission
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - !Ref awsPolicyParameterOne